# Site settings
title: willcode.co
email: willcodeco@proton.me
url: https://willcode.co
description: Development

# Color settings (hex-codes without the leading hash-tag)
color:
  primary-dark: '#000000'
  links: '#219ab3'

# Footer settings
footer: willcode.co

# Build settings
markdown: kramdown
permalink: pretty
